name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: delete .net tests
      run: |
        cd tests
        rm -r EasyCrypto.Tests.Net
        cd ..
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: |
        cd tests
        cd EasyCrypto.Tests
        dotnet restore
    - name: Build
      run: |
        cd tests\EasyCrypto.Tests
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd tests\EasyCrypto.Tests
        dotnet test --no-restore --verbosity normal
